### ISSUE TITLE
6.0.0 installation errors

### ISSUE THREAD

**Issue by drschenk** [DOI-USGS/ISIS3#4925]
**ISIS version(s) affected**: 6.0.0

**Description**  
currently running 5.0.1 on macair 10.15.7:  tried "conda install isis=6.0.0" but it said miniconda3 was out of date so I ran the command it said to run (sorry I cant restore that command in the shell for some reason to see what it said), but it did run 'successfully'.  
now I try "conda install isis=6.0.0" and get:

Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
    should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
    return cuda_detect()
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
        return cuda_detect()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /opt/miniconda3/bin/conda install isis=6.0.0`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment]
It looks like your Anaconda install got messed up some how. Can you try making a new environment and then installing a simple package like CSPICE? Here's the commands for that

```
conda deactivate
conda create -n cspice_test
// You'll need to enter y here
conda activate cspice_test
conda install -c conda-forge cspice
// You'll need to enter y again here
```

See if that will run without error for you.

**Comment by drschenk** [comment]
will that deactivate my current isis environment?   perhaps we should try the conda update again?  except I cant recall what the command was...

**Comment by drschenk** [comment]
I apparently used "conda update -n base -c defaults conda"

also current version is:   conda 4.12.0

**Comment by jessemapel** [comment]
> will that deactivate my current isis environment? perhaps we should try the conda update again? except I cant recall what the command was...

Yes this will deactivate your current ISIS environment and install cspice into a fresh environment. Don't worry about deactivating, you can always re-activate the environment.

I wouldn't try to update conda again yet. Let's check if your install even works first.

**Comment by drschenk** [comment]
so long as I can restore by the end of the day

**Comment by drschenk** [comment]
(isis) MBA-PSchenk-20:icy pschenk$ conda deactivate
(base) MBA-PSchenk-20:icy pschenk$ conda create -n cspice_test
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
    should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
    return cuda_detect()
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
        return cuda_detect()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /opt/miniconda3/bin/conda create -n cspice_test`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: // You'll need to enter y here
conda activate cspice_test
conda install -c conda-forge cspice
// You'll need to enter y again here
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


(base) MBA-PSchenk-20:icy pschenk$ conda activate cspice_test
Could not find conda environment: cspice_test
You can list all discoverable environments with `conda info --envs`.

(base) MBA-PSchenk-20:icy pschenk$ conda install -c conda-forge cspice
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
    should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
    return cuda_detect()
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
        return cuda_detect()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /opt/miniconda3/bin/conda install -c conda-forge cspice`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: // You'll need to enter y again heren

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

**Comment by jessemapel** [comment]
Yeah it looks like your Anaconda install got broken when you updated. Try the update command again and see if that gets the same error.

**Comment by drschenk** [comment]
which is correct update command?

**Comment by drschenk** [comment]
tried this:

`$ /opt/miniconda3/bin/conda update -n base conda`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by jessemapel** [comment]
Try `conda update -n base -c conda-forge conda`
You may need to run `conda activate` prior to this

**Comment by drschenk** [comment]
same garbage. (including conda activate):

(base) MBA-PSchenk-20:~ root# conda update -n base -c conda-forge conda
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
    install(args, parser, 'update')
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
    should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
    return cuda_detect()
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
        return cuda_detect()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /opt/miniconda3/bin/conda update -n base -c conda-forge conda`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by jessemapel** [comment]
Okay, you're going to need to either reach out to the anaconda team and see if there's a way to fix this, or re-install anaconda :(

**Comment by drschenk** [comment]
how do I reach them?

it seems odd I can continue to run isis5.0.1 but not upgrade.  (which I need for mvic framing images)

**Comment by jessemapel** [comment]
You can post a bug report on their GitHub https://github.com/Anaconda-Platform/anaconda-client

**Comment by jessemapel** [comment]
I'm going to close this as it appears to be an Anaconda installation issue. If this continues after your get your Anaconda install fixed, please re-open.

**Comment by drschenk** [comment]
Hi Jesse
Mike says you might be available tmrw.  I have a window between 10 and 11.  Would that work?   My question is getting anaconda to upload and activate so I can get isis 6 up.   Also interested in whether you might know about specific camera models in isis.
Cheers
Paul

Sent from my iPhone!  Typing erratic.

On Apr 28, 2022, at 9:17 AM, Jesse Mapel ***@***.***> wrote:

﻿
        CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I'm going to close this as it appears to be an Anaconda installation issue. If this continues after your get your Anaconda install fixed, please re-open.

**Comment by jessemapel** [comment]
@drschenk Yeah I'll be available then, send me an e-mail or have Mike setup a meeting.

**Comment by drschenk** [comment]
jesse,
i tried flipping sign on  transx and itranss, but that was not good as the longitudes were then reversed.  should have guessed that one.  tried reversing sign on k1 and k2 but may have made things worse.  (note that i am currently working only with 61500 mode images.
not sure what to do with the OFFSET value which is currently =1 for 61500.  what is that parameter?  should it be center of frame? or is it offset from the center?
cheers
paul

Paul Schenk  (2021 AGU Fred Whipple Awardee)
Lunar & Planetary Institute / USRA
3600 Bay Area Blvd.
Houston TX 77058
281-486-2157 (office:  tho I don't often use that)
________________________________

**Comment by jessemapel** [comment]
The OFFSETs are the number or rows between the top of the detector and the portion that was read out for that filter.

**Comment by drschenk** [comment]
Jesse
I was able to install this morning - turns out that my old mini condo was blocking any new install.  I still have a question about the camera models for Juno and whether a fix is required.  Would u be able to discuss that?   If not we can cancel todays zoom and I will contact Stuart or the appropriate individual
Thanks
Paul


Sent from my iPhone!  Typing erratic.

On May 24, 2022, at 3:37 PM, Jesse Mapel ***@***.***> wrote:

﻿
        CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@drschenk<https://github.com/drschenk> Yeah I'll be available then, send me an e-mail or have Mike setup a meeting.
