### ISSUE TITLE
Cannot create an ISIS3 conda environment using the instructions on the wiki

### ISSUE THREAD

**Issue by krlberry** [DOI-USGS/ISIS3#499]
Using a fresh install of anaconda on a new laptop running Fedora 28, I tried to create a conda environment using the environment.yml file in the ISIS3 directory of a fresh git clone and the error message below was the result. 

Has anyone else used the environment.yml file to setup their environment or is everyone else using something internal? And, is there a specific version of conda I should be using? (I'm using `4.5.11`) 

```
(base) bash-4.4$ conda env create -f environment.yml -n ISIS3
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/kberry/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /home/kberry/anaconda3/bin/conda-env create -f environment.yml -n ISIS3`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/kberry/anaconda3/bin/conda
             CONDA_PREFIX=/home/kberry/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/kberry/anaconda3/bin/python
               CONDA_ROOT=/home/kberry/anaconda3
              CONDA_SHLVL=1
                  MANPATH=/usr/share/lmod/lmod/share/man:
               MODULEPATH=/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/
                          usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
                     PATH=/home/kberry/anaconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/b
                          in:/bin:/usr/local/sbin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : base
    active env location : /home/kberry/anaconda3
            shell level : 1
       user config file : /home/kberry/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/kberry/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/kberry/anaconda3/pkgs
                          /home/kberry/.conda/pkgs
       envs directories : /home/kberry/anaconda3/envs
                          /home/kberry/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.18.10-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 76399:1800
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

**Comment by krlberry** [comment]
Fixed my own issue. Looks like the anaconda channel was deprecated: https://github.com/conda/conda/issues/7872 and that using it in the environment.yml causes conda env create to crash.
